### ISSUE TITLE
highlight.js v11 support?

### ISSUE THREAD

**Issue by NullVoxPopuli** [remarkjs/remark-highlight.js#38] opened 2021-06-21 20:41 UTC
### Subject of the issue

remark-highlight.js is using an old version of lowlight and subsequently, highlight.js.
when using "resolutions" to force lowlight and highlight.js to be the latest versions, I get this error:
```
Must use import to load ES Module: .../node_modules/lowlight/index.js
require() of ES modules is not supported.
require() of .../node_modules/lowlight/index.js from 
.../node_modules/remark-highlight.js/dist/index.js is an ES module file as it is a .js file whose nearest parent 
package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename .../node_modules/lowlight/index.js to end in .cjs, change the requiring code to use import(), 
or remove "type": "module" from .../node_modules/lowlight/package.json.
```

Lowlight is already type: module: https://github.com/wooorm/lowlight/blob/main/package.json#L28

### Your environment

*   **OS**: Ubuntu 20.04
*   **Packages**: remark-highlight.js 6.0.0, highlight.js 11.0.1, lowlight 2.0.1
*   **Env**: 
node: 14.17.0
yarn: 1.22.0

### Steps to reproduce

in package.json
```
"resolutions": {
    "highlight.js": "11.0.1",
    "lowlight": "2.0.1",
}
```
// anywhere
```js
require('remark-highlight.js');
```

**Comment by ChristianMurphy** [comment] 2021-06-21 21:26
Right, unfied is moving towards ESM, starting at lower level packages and moving up to high level ones, see https://github.com/unifiedjs/unified/issues/121
The changes are still making their way through the ecosystem, `remark-lighlight.js` as not yet been updated.

This is not a bug, as lowlight 2 is not yet supported here, as noted by the versions package.json file, but support is coming.

**Closed by ChristianMurphy** 2021-06-21 21:26 UTC
Labels: 🐛 type/bug, 🔍 status/open
